### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by HideyukiKamiyama** [HideyukiKamiyama/music_map#152]
## 各種情報
Melody Map
https://www.melody-map.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録
- [x] ログイン、ログアウト
- [x] 聖地機能
  - [x] 聖地一覧機能
    - [x] ブックマーク機能
  - [x] 聖地詳細表示
  - [x] 聖地投稿機能（ミュージックビデオのロケ地、サインのあるお店、その他でタグ付け）
  - [x] 聖地編集機能
- [ ] 一つ一つの聖地に対する投稿機能
  - [ ] 投稿一覧表示機能
  - [ ] 投稿詳細表示（マップ表示）
  - [ ] 投稿機能（タイトル、テキスト、画像、地図座標を保存できるようにする）
  - [ ] 投稿編集機能
  - [ ] 投稿削除機能
- [ ] 検索機能（オートコンプリート）
  - [x] 聖地検索（アーティスト名、タグの種類）
  - [ ] 投稿検索（アーティスト名、地域）

### 作らなくなった機能
**一つ一つの聖地に対する投稿機能**
アプリの作りが分かりにくいと考え投稿機能を廃止し、元々投稿機能に実装しようと考えていた以下の機能を聖地機能に集約しました。そのため上記のMVPリリース時点で実装予定だった投稿に関する機能は実装しておりません。

- 画像投稿機能
- マップ機能
- テキスト機能（spotsテーブルのdetailに該当）

### 追加した機能
- 聖地登録機能に追加した機能
  - マップ機能
  - 画像投稿機能
  - 投稿時のアーティスト名のオートコンプリート機能
- 正確なアーティスト名が投稿されているか確認するカスタムバリデーション（SpotifyAPIを利用）
- コメント機能
- Xでシェア機能

### 一覧画面（マップ表示）
[![Image from Gyazo](https://i.gyazo.com/8e2a375e6d6d240061ecd7ad0ff49d04.png)](https://gyazo.com/8e2a375e6d6d240061ecd7ad0ff49d04)
### 一覧画面（リスト表示）
[![Image from Gyazo](https://i.gyazo.com/31ffb99c94b489a75e3371d7473c5d29.png)](https://gyazo.com/31ffb99c94b489a75e3371d7473c5d29)
### 詳細画面
[![Image from Gyazo](https://i.gyazo.com/8045607ba19c18034ce3ac5339831649.png)](https://gyazo.com/8045607ba19c18034ce3ac5339831649)

お手数をお掛けいたしました。
ご確認のほどよろしくお願いいたします。

**Comment by tarakish** [comment]
確認させていただきました。概ね実装できていると思います！
一点だけ「Xでシェア機能」について
こちら自身の投稿のみシェアボタンが表示されているようですが、この仕様で合っているかご確認いただけますか？

**Comment by HideyukiKamiyama** [comment]
ご確認いただきありがとうございます！
現状では投稿者の意思に反してシェアされることを防ぐためこのような仕様にしております。
MVPリリース後に他の方の投稿もシェアできるようにしたいという要望がありましたら変更を検討しようと思います！

**Comment by tarakish** [comment]
> 現状では投稿者の意思に反してシェアされることを防ぐためこのような仕様にしております。
MVPリリース後に他の方の投稿もシェアできるようにしたいという要望がありましたら変更を検討しようと思います！

理解しました。良いと思います、LGTMです！
現状URLを貼り付けることで共有はできてしまうので、それも防ぐ必要があると判断した場合はサービス内or共有リンク以外からのアクセスをリダイレクトする処理などがあってもよいかと思いますー！

**Comment by HideyukiKamiyama** [comment]
ご確認いただきありがとうございます！
その視点は無かったので参考にさせていただきます！！
