### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by HideyukiKamiyama** [HideyukiKamiyama/music_map#4]
issueを作成いたしました。
ご確認のほどよろしくお願いいたします。

[Project URL](https://github.com/users/HideyukiKamiyama/projects/1)

### 実装予定の機能(MVP時点)
- [ ] ユーザー関連
  - [ ] 会員登録機能
  - [ ] ログイン、ログアウト機能
  - [ ] マイページ機能
- [ ] 聖地関連
  - [ ] 聖地登録機能
  - [ ] 聖地一覧機能
    - [ ] 検索機能
      - [ ] オートコンプリート機能
    - [ ] ブックマーク機能
    - [ ] ページネーション機能
  - [ ] 聖地詳細機能
  - [ ] 聖地編集機能
- [ ] 投稿関連
  - [ ] 投稿機能
      - [ ] 写真投稿機能
      - [ ] Googleマップ上におけるマーカードラッグによる位置座標登録機能
  - [ ] 聖地詳細画面での投稿一覧機能
  - [ ] 投稿詳細機能
  - [ ] 投稿編集機能
  - [ ] 投稿削除機能
  - [ ] マップ上での一覧表示、検索機能
    - [ ] オートコンプリート機能

### 必要なページ
- [ ] トップページ
- [ ] ユーザー関連
  - [ ] 会員登録
  - [ ] ログインページ
  - [ ] マイページ
  - [ ] マイページ編集
- [ ] 聖地関連
  - [ ] 聖地一覧
  - [ ] 聖地詳細
  - [ ] 聖地投稿
  - [ ] 聖地編集
- [ ] 投稿関連
  - [ ] 投稿ページ
  - [ ] 投稿詳細
  - [ ] 投稿編集
  - [ ] 投稿マップ検索
- [ ] ブックマーク一覧
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by Tsuchiya2** [comment]
<img width="683" alt="スクリーンショット 2023-12-21 18 11 26" src="https://github.com/HideyukiKamiyama/music_map/assets/61481161/fdcdcd8f-dd4c-4dbf-b10a-dbe047338090">

projectから看板・issue・ストーリーポイントが確認できるようにした上で提出をお願いいたします。

**Comment by HideyukiKamiyama** [comment]
土屋講師

大変失礼いたしました。
修正いたしましたのでご確認のほどよろしくお願いいたします。

**Comment by tarakish** [comment]
見れるようになりました👍
LGTMです！
5ptのもの（写真の保存先を外部ストレージに変更、聖地検索機能など）は不明点が多いという理由でptが高いと思いますが、実装前のタイミングでは3pt以下の粒度に分割できるとシンプルになり、実装もやりやすいと思いますのでご検討いただければと思います。

**Comment by HideyukiKamiyama** [comment]
宮本講師

ご確認いただきありがとうございます。
実装を進めつつポイントが高いものは見直してみようと思います。
こちらでこのissueはcloseさせていただこうと思います。
